AWSTemplateFormatVersion: 2010-09-09
Description: "Infra Api vehicle services mediation"
  
Parameters:
  AppName:
    Description: The name of the application
    Type: String

  AppEnv:
    Description: The name of the application environment
    Type: String
    AllowedValues:
      - dev
      - nonprod
      - uat
      - prod
  
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccelerateConfiguration:
        AccelerationStatus: "String"
      AccessControl: "String"
      AnalyticsConfigurations: 
        - Id: "String"
          Prefix: "String"
          StorageClassAnalysis:
            DataExport:
              Destination:
                BucketAccountId: "String"
                BucketArn: "String"
                Format: "String"
                Prefix: "String"
              OutputSchemaVersion: "String"
          TagFilters:
            - Key: "String"
              Value: "String"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: false
            ServerSideEncryptionByDefault:
              KMSMasterKeyID: "String"
              SSEAlgorithm: "String"
      BucketName: "String"
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "String"
            AllowedMethods:
              - "String"
            AllowedOrigins:
              - "String"
            ExposedHeaders:
              - "String"
            Id: "String"
            MaxAge: "Number"
      IntelligentTieringConfigurations: 
        - Id: "String"
          Prefix: "String"
          Status: "String"
          TagFilters:
            - Key: "String"
              Value: "String"
          Tierings:
            - AccessTier: "String"
              Days: "Number"
      InventoryConfigurations: 
        - Destination:
            BucketAccountId: "String"
            BucketArn: "String"
            Format: "String"
            Prefix: "String"
          Enabled: false
          Id: "String"
          IncludedObjectVersions: "String"
          OptionalFields:
            - "String"
          Prefix: "String"
          ScheduleFrequency: "String"
      LifecycleConfiguration:
        Rules:
          - AbortIncompleteMultipartUpload:
              DaysAfterInitiation: "Number"
            ExpirationDate: "String"
            ExpirationInDays: "Number"
            ExpiredObjectDeleteMarker: false
            Id: "String"
            NoncurrentVersionExpiration:
              NewerNoncurrentVersions: "Number"
              NoncurrentDays: "Number"
            NoncurrentVersionExpirationInDays: "Number"
            NoncurrentVersionTransition:
              NewerNoncurrentVersions: "Number"
              StorageClass: "String"
              TransitionInDays: "Number"
            NoncurrentVersionTransitions:
              - NewerNoncurrentVersions: "Number"
                StorageClass: "String"
                TransitionInDays: "Number"
            ObjectSizeGreaterThan: "String"
            ObjectSizeLessThan: "String"
            Prefix: "String"
            Status: "String"
            TagFilters:
              - Key: "String"
                Value: "String"
            Transition:
              StorageClass: "String"
              TransitionDate: "String"
              TransitionInDays: "Number"
            Transitions:
              - StorageClass: "String"
                TransitionDate: "String"
                TransitionInDays: "Number"
        TransitionDefaultMinimumObjectSize: "String"
      LoggingConfiguration:
        DestinationBucketName: "String"
        LogFilePrefix: "String"
        TargetObjectKeyFormat:
          PartitionedPrefix:
            PartitionDateSource: "String"
          SimplePrefix: "JSON"
      MetadataConfiguration:
        Destination:
          TableBucketArn: "String"
          TableBucketType: "String"
          TableNamespace: "String"
        InventoryTableConfiguration:
          ConfigurationState: "String"
          EncryptionConfiguration:
            KmsKeyArn: "String"
            SseAlgorithm: "String"
          TableArn: "String"
          TableName: "String"
        JournalTableConfiguration:
          EncryptionConfiguration:
            KmsKeyArn: "String"
            SseAlgorithm: "String"
          RecordExpiration:
            Days: "Number"
            Expiration: "String"
          TableArn: "String"
          TableName: "String"
      MetadataTableConfiguration:
        S3TablesDestination:
          TableArn: "String"
          TableBucketArn: "String"
          TableName: "String"
          TableNamespace: "String"
      MetricsConfigurations: 
        - AccessPointArn: "String"
          Id: "String"
          Prefix: "String"
          TagFilters:
            - Key: "String"
              Value: "String"
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: false
        LambdaConfigurations:
          - Event: "String"
            Filter:
              S3Key:
                Rules:
                  - Name: "String"
                    Value: "String"
            Function: "String"
        QueueConfigurations:
          - Event: "String"
            Filter:
              S3Key:
                Rules:
                  - Name: "String"
                    Value: "String"
            Queue: "String"
        TopicConfigurations:
          - Event: "String"
            Filter:
              S3Key:
                Rules:
                  - Name: "String"
                    Value: "String"
            Topic: "String"
      ObjectLockConfiguration:
        ObjectLockEnabled: "String"
        Rule:
          DefaultRetention:
            Days: "Number"
            Mode: "String"
            Years: "Number"
      ObjectLockEnabled: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: "String"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      ReplicationConfiguration:
        Role: "String"
        Rules:
          - DeleteMarkerReplication:
              Status: "String"
            Destination:
              AccessControlTranslation:
                Owner: "String"
              Account: "String"
              Bucket: "String"
              EncryptionConfiguration:
                ReplicaKmsKeyID: "String"
              Metrics:
                EventThreshold:
                  Minutes: "Number"
                Status: "String"
              ReplicationTime:
                Status: "String"
                Time:
                  Minutes: "Number"
              StorageClass: "String"
            Filter:
              And:
                Prefix: "String"
                TagFilters:
                  - Key: "String"
                    Value: "String"
              Prefix: "String"
              TagFilter:
                Key: "String"
                Value: "String"
            Id: "String"
            Prefix: "String"
            Priority: "Number"
            SourceSelectionCriteria:
              ReplicaModifications:
                Status: "String"
              SseKmsEncryptedObjects:
                Status: "String"
            Status: "String"
      Tags: 
        - Key: "String"
          Value: "String"
      VersioningConfiguration:
        Status: "String"
      WebsiteConfiguration:
        ErrorDocument: "String"
        IndexDocument: "String"
        RedirectAllRequestsTo:
          HostName: "String"
          Protocol: "String"
        RoutingRules:
          - RedirectRule:
              HostName: "String"
              HttpRedirectCode: "String"
              Protocol: "String"
              ReplaceKeyPrefixWith: "String"
              ReplaceKeyWith: "String"
            RoutingRuleCondition:
              HttpErrorCodeReturnedEquals: "String"
              KeyPrefixEquals: "String"

  Api:
    Type: AWS::Serverless::Api
    Properties:
      AccessLogSetting: AccessLogSetting
      AlwaysDeploy: Boolean
      ApiKeySourceType: "String"
      Auth: ApiAuth
      BinaryMediaTypes: List
      CacheClusterEnabled: Boolean
      CacheClusterSize: "String"
      CanarySetting: CanarySetting
      Cors: String|CorsConfiguration
      DefinitionBody: JSON
      DefinitionUri: String|ApiDefinition
      Description: "String"
      DisableExecuteApiEndpoint: Boolean
      Domain: DomainConfiguration
      EndpointConfiguration: EndpointConfiguration
      FailOnWarnings: Boolean
      GatewayResponses: Map
      MergeDefinitions: Boolean
      MethodSettings: MethodSettings
      MinimumCompressionSize: Number
      Mode: "String"
      Models: Map
      Name: "String"
      OpenApiVersion: "String"
      PropagateTags: Boolean
      StageName: "String" # Required
      Tags: Map
      TracingEnabled: Boolean
      Variables: Map

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions: 
        - AttributeName: "String"
          AttributeType: "String"
      BillingMode: "String"
      ContributorInsightsSpecification:
        Enabled: false
        Mode: "String"
      DeletionProtectionEnabled: false
      GlobalSecondaryIndexes: 
        - ContributorInsightsSpecification:
            Enabled: false
            Mode: "String"
          IndexName: "String"
          KeySchema:
            - AttributeName: "String"
              KeyType: "String"
          OnDemandThroughput:
            MaxReadRequestUnits: "Number"
            MaxWriteRequestUnits: "Number"
          Projection:
            NonKeyAttributes:
              - "String"
            ProjectionType: "String"
          ProvisionedThroughput:
            ReadCapacityUnits: "Number"
            WriteCapacityUnits: "Number"
          WarmThroughput:
            ReadUnitsPerSecond: "Number"
            WriteUnitsPerSecond: "Number"
      GlobalTableSettingsReplicationMode: "String"
      ImportSourceSpecification:
        InputCompressionType: "String"
        InputFormat: "String"
        InputFormatOptions:
          Csv:
            Delimiter: "String"
            HeaderList:
              - "String"
        S3BucketSource:
          S3Bucket: "String"
          S3BucketOwner: "String"
          S3KeyPrefix: "String"
      KeySchema: # Required
        - AttributeName: "String"
          KeyType: "String"
      KinesisStreamSpecification:
        ApproximateCreationDateTimePrecision: "String"
        StreamArn: "String"
      LocalSecondaryIndexes: 
        - IndexName: "String"
          KeySchema:
            - AttributeName: "String"
              KeyType: "String"
          Projection:
            NonKeyAttributes:
              - "String"
            ProjectionType: "String"
      OnDemandThroughput:
        MaxReadRequestUnits: "Number"
        MaxWriteRequestUnits: "Number"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
        RecoveryPeriodInDays: "Number"
      ProvisionedThroughput:
        ReadCapacityUnits: "Number"
        WriteCapacityUnits: "Number"
      ResourcePolicy:
        PolicyDocument: "JSON"
      SSESpecification:
        KMSMasterKeyId: "String"
        SSEEnabled: false
        SSEType: "String"
      StreamSpecification:
        ResourcePolicy:
          PolicyDocument: "JSON"
        StreamViewType: "String"
      TableClass: "String"
      TableName: "String"
      Tags: 
        - Key: "String"
          Value: "String"
      TimeToLiveSpecification:
        AttributeName: "String"
        Enabled: false
      WarmThroughput:
        ReadUnitsPerSecond: "Number"
        WriteUnitsPerSecond: "Number"
  
  Lambda:
    Type: AWS::Serverless::Function
    Properties:
      Architectures: List
      AssumeRolePolicyDocument: JSON
      AutoPublishAlias: "String"
      AutoPublishAliasAllProperties: Boolean
      AutoPublishCodeSha256: "String"
      CodeSigningConfigArn: "String"
      CodeUri: String|FunctionCode
      DeadLetterQueue: Map|DeadLetterQueue
      DeploymentPreference: DeploymentPreference
      Description: "String"
      Environment: Environment
      EphemeralStorage: EphemeralStorage
      EventInvokeConfig: EventInvokeConfiguration
      Events: EventSource
      FileSystemConfigs: List
      FunctionName: "String"
      FunctionUrlConfig: FunctionUrlConfig
      Handler: "String"
      ImageConfig: ImageConfig
      ImageUri: "String"
      InlineCode: "String"
      KmsKeyArn: "String"
      Layers: List
      LoggingConfig: LoggingConfig
      MemorySize: Number
      PackageType: "String"
      PermissionsBoundary: "String"
      Policies: String|List|Map
      PropagateTags: Boolean
      ProvisionedConcurrencyConfig: ProvisionedConcurrencyConfig
      ReservedConcurrentExecutions: Number
      Role: "String"
      RolePath: "String"
      Runtime: "String"
      RuntimeManagementConfig: RuntimeManagementConfig
      SnapStart: SnapStart
      Tags: Map
      Timeout: Number
      Tracing: "String"
      VersionDescription: "String"
      VpcConfig: VpcConfig
    
Outputs: 
  S3BucketName:
    Description: S3 Bucket Name
    Value: !Ref S3Bucket
  
  S3BucketArn:
    Description: S3 Bucket Arn
    Value: !GetAtt S3Bucket.Arn
  
  ApiID:
    Description: API ID
    Value: !Ref Api

  LambdaName:
    Description: Lambda Name
    Value: !Ref Lambda
  
  LambdaArn:
    Description: Lambda Name
    Value: !GetAtt Lambda.Arn

  DynamoDBTableName:
    Description: Dynamo Table Name
    Value: !Ref DynamoDBTable

  DynamoDBTableArn:
    Description: Dynamo Table Arn
    Value: !GetAtt DynamoDBTable.Arn